# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x13smartspeech.task.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"!\n\x0eGetTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"$\n\x11\x43\x61ncelTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"\xad\x02\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12.\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x06status\x18\x04 \x01(\x0e\x32 .smartspeech.task.v1.Task.Status\x12\x0f\n\x05\x65rror\x18\x05 \x01(\tH\x00\x12\x1a\n\x10response_file_id\x18\x06 \x01(\tH\x00\"P\n\x06Status\x12\r\n\tUNDEFINED\x10\x00\x12\x07\n\x03NEW\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\x0c\n\x08\x43\x41NCELED\x10\x03\x12\x08\n\x04\x44ONE\x10\x04\x12\t\n\x05\x45RROR\x10\x05\x42\x08\n\x06result2\xa9\x01\n\x0bSmartSpeech\x12I\n\x07GetTask\x12#.smartspeech.task.v1.GetTaskRequest\x1a\x19.smartspeech.task.v1.Task\x12O\n\nCancelTask\x12&.smartspeech.task.v1.CancelTaskRequest\x1a\x19.smartspeech.task.v1.TaskBU\n\"ru.sberdevices.smartspeech.task.v1Z/github.com/sberdevices/smartspeech/task/v1;taskb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"ru.sberdevices.smartspeech.task.v1Z/github.com/sberdevices/smartspeech/task/v1;task'
  _globals['_GETTASKREQUEST']._serialized_start=68
  _globals['_GETTASKREQUEST']._serialized_end=101
  _globals['_CANCELTASKREQUEST']._serialized_start=103
  _globals['_CANCELTASKREQUEST']._serialized_end=139
  _globals['_TASK']._serialized_start=142
  _globals['_TASK']._serialized_end=443
  _globals['_TASK_STATUS']._serialized_start=353
  _globals['_TASK_STATUS']._serialized_end=433
  _globals['_SMARTSPEECH']._serialized_start=446
  _globals['_SMARTSPEECH']._serialized_end=615
# @@protoc_insertion_point(module_scope)
